export const SEARCH_SUPER_HERO = 'SEARCH_SUPER_HERO';
export const SEARCH_SUPER_HERO_SUCCESS = 'SEARCH_SUPER_HERO_SUCCESS';
export const SEARCH_SUPER_HERO_FAILED = 'SEARCH_SUPER_HERO_FAILED';

export const SUPER_HERO_DETAIL = 'SUPER_HERO_DETAIL';
export const SUPER_HERO_DETAIL_SUCCESS = 'SUPER_HERO_DETAIL_SUCCESS';
export const SUPER_HERO_DETAIL_FAILT = 'SUPER_HERO_DETAIL_FAILT';
export const RESET_SUPER_HERO_DETAIL = 'RESET_SUPER_HERO_DETAIL';

export const UPDATE_FAVORITE_LIST = 'ADD_FAVORITE';

export const RESET_FAVORITE_LIST = 'REMOVE_FAVORITE';

export const ADD_NEW_SUPER_HERO = 'ADD_NEW_SUPER_HERO';
export const ADD_NEW_SUPER_HERO_SUCCESS = 'ADD_NEW_SUPER_HERO_SUCCESS';
export const ADD_NEW_SUPER_HERO_FAILED = 'ADD_NEW_SUPER_HERO_FAILED';
