export const GET_ALL_SUPER_HEROS = "GET_ALL_SUPER_HEROS";
export const GET_ALL_SUPER_HEROS_SUCCESS = "GET_ALL_SUPER_HERO_SUCCESS";
export const GET_ALL_SUPER_HEROS_FAILED = "GET_ALL_SUPER_HEROS_FAILED";

export const GET_SUPER_HEROS = "GET_SUPER_HEROS";
export const GET_SUPER_HEROS_BY_NAME = "GET_SUPER_HEROS_BY_NAME";
export const GET_SUPER_HEROS_BY_ID = "GET_SUPER_HEROS_BY_ID";

export const GET_SUPER_HERO_DETAIL = "GET_SUPER_HERO_DETAIL";

export const UPDATE_FAVORITE_STATUS = "UPDATE_FAVORITE_STATUS";

export const RESET_FAVORITE_LIST = "REMOVE_FAVORITE";

export const ADD_NEW_SUPER_HERO = "ADD_NEW_SUPER_HERO";
export const ADD_NEW_SUPER_HERO_SUCCESS = "ADD_NEW_SUPER_HERO_SUCCESS";
export const ADD_NEW_SUPER_HERO_FAILED = "ADD_NEW_SUPER_HERO_FAILED";
